version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:24.12.0"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'         
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: |
           echo "Install dependencies in the the backend API  "
           npm run api:install
      # Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            echo "Lint the frontend"
            npm run frontend:lint
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "Build the frontend app"
            npm run frontend:build
      # Build the backend API      
      - run:
          name: API Build
          command: |
            echo "Build the backend API"
            npm run api:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '24.12.0' 
      - eb/setup
      - aws-cli/setup
      - checkout

      - run:
          name: Configure AWS Profile
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
            aws configure set aws_session_token $AWS_SESSION_TOKEN --profile default
            aws configure set region $AWS_REGION --profile default
      # Send secrets from CircleCI to Elastic Beanstalk
      - run:
          name: Set Elastic Beanstalk Environment Variables
          command: |
            aws elasticbeanstalk update-environment \
              --environment-name Udacity-udagram-api-env \
              --option-settings \
                Namespace=aws:elasticbeanstalk:application:environment,OptionName=POSTGRES_USERNAME,Value=$POSTGRES_USERNAME \
                Namespace=aws:elasticbeanstalk:application:environment,OptionName=POSTGRES_PASSWORD,Value=$POSTGRES_PASSWORD \
                Namespace=aws:elasticbeanstalk:application:environment,OptionName=POSTGRES_DB,Value=$POSTGRES_DB \
                Namespace=aws:elasticbeanstalk:application:environment,OptionName=POSTGRES_HOST,Value=$POSTGRES_HOST \
                Namespace=aws:elasticbeanstalk:application:environment,OptionName=JWT_SECRET,Value=$JWT_SECRET \
              --profile default

            aws elasticbeanstalk wait environment-updated --application-name demo-app --environment-names Udacity-udagram-api-env --profile default
      - run:
          name: Deploy App
          # Install, build, deploy in both apps
          command: |
            echo "Install, build, deploy in both apps"
            npm run deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
 